In [2]:
import pandas as pd
df = pd.read_csv("../data/training_titanic.csv")

In [3]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
651,652,1,2,"Doling, Miss. Elsie",female,18.0,0,1,231919,23.0,NaN,S

In [4]:
df.columns.to_list()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [5]:
df.drop(['PassengerId', 'Name',  'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked' ], axis=1,inplace=True)

In [6]:
df.columns.tolist()

['Survived', 'Pclass', 'Sex', 'Age', 'Fare']

In [7]:
df['Sex'] = df['Sex'].map({
    "male": 1,
    "female": 0
})

In [8]:
df.sample(5)

     Survived  Pclass  Sex   Age     Fare
670         1       2    0  40.0  39.0000
556         1       1    0  48.0  39.6000
751         1       3    1   6.0  12.4750
372         0       3    1  19.0   8.0500
43          1       2    0   3.0  41.5792

In [9]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [10]:
df.sample(10)

     Survived  Pclass  Sex        Age     Fare
838         1       3    1  32.000000  56.4958
840         0       3    1  20.000000   7.9250
566         0       3    1  19.000000   7.8958
432         1       2    0  42.000000  26.0000
559         1       3    0  36.000000  17.4000
472         1       2    0  33.000000  27.7500
104         0       3    1  37.000000   7.9250
564         0       3    0  29.699118   8.0500
494         0       3    1  21.000000   8.0500
160         0       3    1  44.000000  16.1000

In [11]:
y = df.iloc[:, 0:1]
X = df.iloc[:, 1:]
print(X.sample())
print(y.sample())

     Pclass  Sex   Age  Fare
389       2    0  17.0  12.0
     Survived
657         0

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = GaussianNB()
model.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))

Accuracy: 0.7597765363128491
              precision    recall  f1-score   support

           0       0.80      0.79      0.79       105
           1       0.71      0.72      0.71        74

    accuracy                           0.76       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.76      0.76      0.76       179